name: flutter_chat_ui
description: >
  Actively maintained, community-driven chat UI implementation with an
  optional Firebase BaaS.
version: 1.6.10
homepage: https://flyer.chat
repository: https://github.com/flyerhq/flutter_chat_ui

environment:
  sdk: '>=2.19.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  diffutil_dart: ^3.0.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_chat_types: ^3.6.2
  flutter_link_previewer: ^3.2.2
  flutter_parsed_text: ^2.2.1
  intl: '>=0.17.0 <1.0.0'
  meta: '>=1.8.0 <2.0.0'
  photo_view: ^0.14.0
  scroll_to_index: ^3.0.1
  url_launcher: ^6.1.12
  visibility_detector: ^0.4.0+2

dev_dependencies:
  dart_code_metrics: ^5.7.5
  flutter_lints: ^2.0.2
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - lib/assets/icon-arrow.png
    - lib/assets/icon-attachment.png
    - lib/assets/icon-delivered.png
    - lib/assets/icon-document.png
    - lib/assets/icon-error.png
    - lib/assets/icon-seen.png
    - lib/assets/icon-send.png
    - lib/assets/2.0x/icon-arrow.png
    - lib/assets/2.0x/icon-attachment.png
    - lib/assets/2.0x/icon-delivered.png
    - lib/assets/2.0x/icon-document.png
    - lib/assets/2.0x/icon-error.png
    - lib/assets/2.0x/icon-seen.png
    - lib/assets/2.0x/icon-send.png
    - lib/assets/3.0x/icon-arrow.png
    - lib/assets/3.0x/icon-attachment.png
    - lib/assets/3.0x/icon-delivered.png
    - lib/assets/3.0x/icon-document.png
    - lib/assets/3.0x/icon-error.png
    - lib/assets/3.0x/icon-seen.png
    - lib/assets/3.0x/icon-send.png
